apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-ms
  labels:
    app: question-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-ms
  template:
    metadata:
      labels:
        app: question-ms
    spec:
      containers:
        - name: question-ms
          image: islamahmad/eaproj-questionms:1.0.12
          env:
            - name: APP_VERSION
              value: "islamahmad/eaproj-questionms:1.0.12"
            - name: SERVER_PORT
              value: "8080"
#            - name: AUTHENTICATE_SERVICE
#              valueFrom:
#                configMapKeyRef:
#                  name: services-global
#                  key: AUTHENTICATE_SERVICE
#            - name: SERVICE_SECRET
#              valueFrom:
#                configMapKeyRef:
#                  name: services-global
#                  key: SERVICE_SECRET

            #MONGODB
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: question-ms
                  key: MONGODB_PASS

          envFrom:
            - configMapRef:
                name: question-ms
            - configMapRef:
                name: services-global
            - configMapRef:
                name: kafka-global
