apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-ms
  labels:
    app: question-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-ms
  template:
    metadata:
      labels:
        app: question-ms
    spec:
      containers:
        - name: question-ms
          image: islamahmad/question-ms:1.0.0
          ports:
            - containerPort: 8080
          env:
            #MONGODB
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: question-ms
                  key: MONGODB_HOST
            - name: MONGODB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: question-ms
                  key: MONGODB_USERNAME
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: question-ms
                  key: MONGODB_PORT
            - name: MONGODB_PASS
              valueFrom:
                configMapKeyRef:
                  name: question-ms
                  key: MONGODB_PASS
            - name: MONGODB_AUTH
              valueFrom:
                configMapKeyRef:
                  name: question-ms
                  key: MONGODB_AUTH
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: question-ms
                  key: MONGODB_DATABASE
            #KAFKA
            - name: TOPIC_NEW_QUESTION
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: TOPIC_NEW_QUESTION
            - name: SUBS_NEW_QUESTION_COMMENT_TO_QUESTION
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: SUBS_NEW_QUESTION_COMMENT_TO_QUESTION
            - name: SUBS_NEW_ANSWER_COMMENT_TO_QUESTION
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: SUBS_NEW_ANSWER_COMMENT_TO_QUESTION
            - name: SUBS_BANE_QUESTION_TO_QUESTION
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: SUBS_BANE_QUESTION_TO_QUESTION
            - name: SUBS_UPDATE_QUESTION_COMMENT_TO_QUESTION
              valueFrom:
                configMapKeyRef:
                  name: kafka-global
                  key: SUBS_UPDATE_QUESTION_COMMENT_TO_QUESTION

            - name: AUTHENTICATE_SERVICE
                valueFrom:
                  configMapKeyRef:
                    name: question-ms
                    key: AUTHENTICATE_SERVICE
